project:
    project_name: mock_project
    description: mock_description
    version: mock_version

input:
    source_type: local # couldbe mock, local, sftp, s3
    config:
        # In case of sftp, use the following format
        #sftp_host: radar-base-nas.brc.iop.kcl.ac.uk
        #sftp_source_path: /mnt/pool0/radar-prod-k8s-aws-output/output/RADAR-ARTCARMA-KCL-s1/
        #sftp_username: hsankesa
        #sftp_private_key: ~/.ssh/id_rsa
        #sftp_target_path: output/sample_data_pass/
        # In case of s3, use the following format
        #       aws_access_key_id:
        #       aws_secret_access_key:
        #       region_name:
        #       s3_access_url:
        #       bucket:
        #       prefix:
        # In case of local or Mock, use the following format
        source_path: /Users/heetsankesara/work/RADAR/radar-pipeline/participantsummary/output/sample_data_pass/
    data_format: csv

configurations:
    df_type: 'pandas'
    #user_sampling:
        ## Possible methods: fraction, count, userid
    #    method: fraction
    #    config:
    #        fraction: 0.8
        #method: count
        #config:
        #    count: 4
        #method: userid
        #config:
        #    userids:
        #        - 2a02e53a-951e-4fd0-b47f-195a87096bd0
    ## TODO: For future
    #data_sampling:
        ## Possible methods:  time, count, fraction
        ## starttime and endtime format is dd-mm-yyyy hh:mm:ss in UTC timezone
        ## It is possible to have multiple time ranges. See below Example
        #method: time
        #config:
        #- starttime: 2018-11-22 00:00:00
        #  endtime:  2018-11-26 00:00:00
        #  time_column: value.time
        #- starttime: 2018-12-27 00:00:00
        #  time_column: value.time
        #method: count
        #config:
        #   count: 100
        #method: fraction
        #config:
        #   fraction: 0.3

features:
    - location: '/Users/heetsankesara/work/RADAR/radar-pipeline/participantsummary'
      feature_groups:
        - ParticipantSummaryActiveData
        - ParticipantSummaryPassiveData
      feature_names:
        - all
        - all

output:
    output_location: local # can be local, postgres, sftp
    config:
        target_path: output/test/
    data_format: csv
    compress: false